# Generated by Django 5.0.1 on 2024-02-02 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
