# Generated by Django 5.0.1 on 2024-02-06 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_rename_customuser_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CustomUser',
        ),
    ]
