# Generated by Django 5.0.1 on 2024-02-06 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_rename_customuser_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='user',
            new_name='user_id',
        ),
    ]
