# Generated by Django 5.0.1 on 2024-02-08 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_task_user_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CustomUser',
        ),
    ]
