# Generated by Django 5.0.1 on 2024-02-12 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_customuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
