# Generated by Django 5.0.1 on 2024-02-12 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(default='In Progress', max_length=100, null=True),
        ),
    ]
